import {
  ArrowLeft,
  ArrowUp,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleUser,
  Cloud,
  Copy,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Folder,
  FolderOpen,
  Files,
  History,
  Info,
  Lock,
  Menu,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Plus,
  RefreshCw,
  Shield,
  TriangleAlert,
} from "lucide-react";

export const ICON_STROKE = 1.75;

export const icons = {
  workspace: Files,
  watch: Eye,
  activity: History,
  runs: History,
  drive: Cloud,
  document: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  account: CircleUser,
  menu: Menu,
  more: MoreHorizontal,
  hide: EyeOff,
  plus: Plus,
  chevronDown: ChevronDown,
  send: ArrowUp,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  externalLink: ExternalLink,
  copy: Copy,
  shield: Shield,
  lock: Lock,
  refresh: RefreshCw,
  success: CheckCircle2,
  warning: TriangleAlert,
  error: CircleAlert,
  info: Info,
  check: Check,
  collapseRail: PanelLeftClose,
  expandRail: PanelLeftOpen,
} as const;
