"""initial production schema

Revision ID: 4db6c7eb34db
Revises:
Create Date: 2026-08-07 17:06:44.014458
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4db6c7eb34db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_connections",
        sa.Column("owner_subject", sa.String(length=255), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("GOOGLE", name="provider", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("provider_account_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "REVOKED",
                "ERROR",
                name="connection_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "granted_scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("credential_reference", sa.String(length=512), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cloud_connections")),
        sa.UniqueConstraint(
            "owner_subject",
            "provider",
            "provider_account_subject",
            name="uq_cloud_connection_owner_provider_account",
        ),
    )
    op.create_index(
        op.f("ix_cloud_connections_owner_subject"),
        "cloud_connections",
        ["owner_subject"],
        unique=False,
    )
    op.create_table(
        "cloud_documents",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("provider_file_id", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column(
            "parent_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("drive_id", sa.String(length=255), nullable=True),
        sa.Column("last_seen_revision_id", sa.Text(), nullable=True),
        sa.Column("last_successful_revision_id", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "provider_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["cloud_connections.id"],
            name=op.f("fk_cloud_documents_connection_id_cloud_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cloud_documents")),
        sa.UniqueConstraint(
            "connection_id", "provider_file_id", name="uq_cloud_document_connection_file"
        ),
    )
    op.create_index(
        op.f("ix_cloud_documents_connection_id"), "cloud_documents", ["connection_id"], unique=False
    )
    op.create_table(
        "watch_configs",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("parent_folder_id", sa.String(length=255), nullable=False),
        sa.Column("schedule", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "default_mode",
            sa.Enum(
                "PREVIEW", "COMMIT", name="sync_mode", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["cloud_connections.id"],
            name=op.f("fk_watch_configs_connection_id_cloud_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_configs")),
        sa.UniqueConstraint("connection_id", "parent_folder_id", name="uq_watch_connection_parent"),
    )
    op.create_index(
        op.f("ix_watch_configs_connection_id"), "watch_configs", ["connection_id"], unique=False
    )
    op.create_table(
        "folder_rules",
        sa.Column("watch_config_id", sa.Uuid(), nullable=False),
        sa.Column("provider_folder_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("instruction_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "supported_formats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_folder_rules_version_positive")),
        sa.ForeignKeyConstraint(
            ["watch_config_id"],
            ["watch_configs.id"],
            name=op.f("fk_folder_rules_watch_config_id_watch_configs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folder_rules")),
        sa.UniqueConstraint(
            "watch_config_id",
            "provider_folder_id",
            "version",
            name="uq_folder_rule_watch_folder_version",
        ),
    )
    op.create_index(
        op.f("ix_folder_rules_watch_config_id"), "folder_rules", ["watch_config_id"], unique=False
    )
    op.create_table(
        "watch_cursors",
        sa.Column("watch_config_id", sa.Uuid(), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=False),
        sa.Column(
            "cursor_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["watch_config_id"],
            ["watch_configs.id"],
            name=op.f("fk_watch_cursors_watch_config_id_watch_configs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_cursors")),
        sa.UniqueConstraint("watch_config_id", name="uq_watch_cursor_config"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("cloud_document_id", sa.Uuid(), nullable=False),
        sa.Column("folder_rule_id", sa.Uuid(), nullable=False),
        sa.Column("folder_rule_version", sa.Integer(), nullable=False),
        sa.Column(
            "rule_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "PREVIEW", "COMMIT", name="sync_mode", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "BASELINING",
                "EDITING",
                "AWAITING_REVIEW",
                "READY_TO_COMMIT",
                "PREVIEW_READY",
                "COMMITTING",
                "VERIFYING",
                "SUCCEEDED",
                "CONFLICT",
                "UNSUPPORTED",
                "SKIPPED",
                "EXPIRED",
                "COMMIT_OUTCOME_UNKNOWN",
                "VERIFICATION_FAILED",
                "FAILED",
                "CANCELLED",
                name="sync_run_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("intent_key", sa.String(length=64), nullable=False),
        sa.Column("baseline_revision_id", sa.Text(), nullable=True),
        sa.Column("precommit_revision_id", sa.Text(), nullable=True),
        sa.Column("resulting_revision_id", sa.Text(), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column(
            "failure_detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("state_version >= 1", name=op.f("ck_sync_runs_state_version_positive")),
        sa.ForeignKeyConstraint(
            ["cloud_document_id"],
            ["cloud_documents.id"],
            name=op.f("fk_sync_runs_cloud_document_id_cloud_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["folder_rule_id"],
            ["folder_rules.id"],
            name=op.f("fk_sync_runs_folder_rule_id_folder_rules"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
        sa.UniqueConstraint("intent_key", name="uq_sync_run_intent_key"),
    )
    op.create_index(
        op.f("ix_sync_runs_cloud_document_id"), "sync_runs", ["cloud_document_id"], unique=False
    )
    op.create_index(
        "ix_sync_runs_document_nonterminal",
        "sync_runs",
        ["cloud_document_id", "state"],
        unique=False,
    )
    op.create_index(op.f("ix_sync_runs_state"), "sync_runs", ["state"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("actor_subject", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column(
            "safe_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["cloud_connections.id"],
            name=op.f("fk_audit_events_connection_id_cloud_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_audit_events_sync_run_id_sync_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_connection_id"), "audit_events", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_sync_run_id"), "audit_events", ["sync_run_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_type_created", "audit_events", ["event_type", "created_at"], unique=False
    )
    op.create_table(
        "external_effects",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("effect_key", sa.String(length=255), nullable=False),
        sa.Column(
            "effect_type",
            sa.Enum(
                "SUPERDOCS_JOB_START",
                "GOOGLE_BACKUP_COPY",
                "GOOGLE_BATCH_UPDATE",
                name="effect_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "NOT_STARTED",
                "STARTED",
                "SUCCEEDED",
                "UNKNOWN",
                name="effect_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "request_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("provider_external_id", sa.String(length=512), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "reconciliation_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_external_effects_attempt_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_external_effects_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_effects")),
        sa.UniqueConstraint("sync_run_id", "effect_key", name="uq_external_effect_run_key"),
    )
    op.create_index(
        op.f("ix_external_effects_sync_run_id"), "external_effects", ["sync_run_id"], unique=False
    )
    op.create_table(
        "run_operations",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("operation_key", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STARTED",
                "SUCCEEDED",
                "FAILED",
                name="operation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("provider_operation_count", sa.Integer(), nullable=True),
        sa.Column(
            "safe_metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_run_operations_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_operations")),
    )
    op.create_index(
        "ix_run_operations_run_stage", "run_operations", ["sync_run_id", "stage"], unique=False
    )
    op.create_index(
        op.f("ix_run_operations_sync_run_id"), "run_operations", ["sync_run_id"], unique=False
    )
    op.create_table(
        "run_transitions",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "QUEUED",
                "BASELINING",
                "EDITING",
                "AWAITING_REVIEW",
                "READY_TO_COMMIT",
                "PREVIEW_READY",
                "COMMITTING",
                "VERIFYING",
                "SUCCEEDED",
                "CONFLICT",
                "UNSUPPORTED",
                "SKIPPED",
                "EXPIRED",
                "COMMIT_OUTCOME_UNKNOWN",
                "VERIFICATION_FAILED",
                "FAILED",
                "CANCELLED",
                name="sync_run_from_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "QUEUED",
                "BASELINING",
                "EDITING",
                "AWAITING_REVIEW",
                "READY_TO_COMMIT",
                "PREVIEW_READY",
                "COMMITTING",
                "VERIFYING",
                "SUCCEEDED",
                "CONFLICT",
                "UNSUPPORTED",
                "SKIPPED",
                "EXPIRED",
                "COMMIT_OUTCOME_UNKNOWN",
                "VERIFICATION_FAILED",
                "FAILED",
                "CANCELLED",
                name="sync_run_to_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_subject", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_run_transitions_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_run_transitions_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_transitions")),
        sa.UniqueConstraint("sync_run_id", "sequence", name="uq_run_transition_sequence"),
    )
    op.create_index(
        op.f("ix_run_transitions_sync_run_id"), "run_transitions", ["sync_run_id"], unique=False
    )
    op.create_table(
        "source_snapshots",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("cloud_document_id", sa.Uuid(), nullable=False),
        sa.Column("provider_revision_id", sa.Text(), nullable=False),
        sa.Column("source_format", sa.String(length=255), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("native_raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("native_canonical_sha256", sa.String(length=64), nullable=False),
        sa.Column("exported_artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=128), nullable=False),
        sa.Column(
            "capability_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "provider_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cloud_document_id"],
            ["cloud_documents.id"],
            name=op.f("fk_source_snapshots_cloud_document_id_cloud_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_source_snapshots_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint("sync_run_id", name="uq_source_snapshot_run"),
    )
    op.create_index(
        op.f("ix_source_snapshots_cloud_document_id"),
        "source_snapshots",
        ["cloud_document_id"],
        unique=False,
    )
    op.create_table(
        "superdocs_sessions",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column(
            "raw_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_superdocs_sessions_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_superdocs_sessions")),
        sa.UniqueConstraint("session_id", name="uq_superdocs_session_external_id"),
        sa.UniqueConstraint("sync_run_id", name="uq_superdocs_session_run"),
    )
    op.create_table(
        "mapping_proofs",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=128), nullable=False),
        sa.Column("mapper_version", sa.String(length=128), nullable=False),
        sa.Column("integrity_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "proof_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_mapping_proofs_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_mapping_proofs_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_proofs")),
        sa.UniqueConstraint(
            "sync_run_id", "integrity_sha256", name="uq_mapping_proof_run_integrity"
        ),
    )
    op.create_index(
        op.f("ix_mapping_proofs_sync_run_id"), "mapping_proofs", ["sync_run_id"], unique=False
    )
    op.create_table(
        "superdocs_documents",
        sa.Column("superdocs_session_id", sa.Uuid(), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "TARGET",
                "REFERENCE",
                name="superdocs_document_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("session_document_id", sa.String(length=255), nullable=False),
        sa.Column("durable_document_id", sa.String(length=255), nullable=True),
        sa.Column("upload_version_id", sa.String(length=255), nullable=False),
        sa.Column("final_version_id", sa.String(length=255), nullable=True),
        sa.Column("baseline_html_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "baseline_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_superdocs_documents_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superdocs_session_id"],
            ["superdocs_sessions.id"],
            name=op.f("fk_superdocs_documents_superdocs_session_id_superdocs_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_superdocs_documents")),
        sa.UniqueConstraint(
            "superdocs_session_id",
            "session_document_id",
            name="uq_superdocs_document_session_local_id",
        ),
    )
    op.create_index(
        op.f("ix_superdocs_documents_superdocs_session_id"),
        "superdocs_documents",
        ["superdocs_session_id"],
        unique=False,
    )
    op.create_table(
        "superdocs_jobs",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("superdocs_session_id", sa.Uuid(), nullable=False),
        sa.Column("target_document_id", sa.Uuid(), nullable=False),
        sa.Column("provider_job_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "awaiting_approval",
                "completed",
                "failed",
                "cancelled",
                name="superdocs_job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("start_request_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "usage_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["superdocs_session_id"],
            ["superdocs_sessions.id"],
            name=op.f("fk_superdocs_jobs_superdocs_session_id_superdocs_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_superdocs_jobs_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_document_id"],
            ["superdocs_documents.id"],
            name=op.f("fk_superdocs_jobs_target_document_id_superdocs_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_superdocs_jobs")),
        sa.UniqueConstraint(
            "superdocs_session_id", "provider_job_id", name="uq_superdocs_job_session_external_id"
        ),
    )
    op.create_index(
        op.f("ix_superdocs_jobs_sync_run_id"), "superdocs_jobs", ["sync_run_id"], unique=False
    )
    op.create_table(
        "write_plans",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_proof_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=128), nullable=False),
        sa.Column("provider_file_id", sa.String(length=255), nullable=False),
        sa.Column("baseline_revision_id", sa.Text(), nullable=False),
        sa.Column("mapper_version", sa.String(length=128), nullable=False),
        sa.Column("verifier_version", sa.String(length=128), nullable=False),
        sa.Column(
            "provider_operations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_postimage_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("integrity_sha256", sa.String(length=64), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mapping_proof_id"],
            ["mapping_proofs.id"],
            name=op.f("fk_write_plans_mapping_proof_id_mapping_proofs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_write_plans_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_write_plans_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_write_plans")),
        sa.UniqueConstraint("integrity_sha256", name="uq_write_plan_integrity"),
        sa.UniqueConstraint("sync_run_id", name="uq_write_plan_run"),
    )
    op.create_table(
        "backups",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("write_plan_id", sa.Uuid(), nullable=False),
        sa.Column("external_effect_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "CREATED",
                "VERIFIED",
                "ORPHANED",
                "FAILED",
                "UNKNOWN",
                name="backup_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_backup_file_id", sa.String(length=255), nullable=True),
        sa.Column("baseline_revision_id", sa.Text(), nullable=False),
        sa.Column("canonical_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "location_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "acl_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["external_effect_id"],
            ["external_effects.id"],
            name=op.f("fk_backups_external_effect_id_external_effects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_backups_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["write_plan_id"],
            ["write_plans.id"],
            name=op.f("fk_backups_write_plan_id_write_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backups")),
        sa.UniqueConstraint("external_effect_id", name="uq_backup_external_effect"),
    )
    op.create_index(op.f("ix_backups_sync_run_id"), "backups", ["sync_run_id"], unique=False)
    op.create_table(
        "review_rounds",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("superdocs_job_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "awaiting_kind",
            sa.Enum(
                "CHANGE_BATCH",
                "CONTINUE_PROMPT",
                name="review_awaiting_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "raw_pending_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "resolution",
            sa.Enum(
                "SUBMIT_CHANGES",
                "CONTINUE",
                "STOP",
                name="review_round_resolution",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("resolved_by_subject", sa.String(length=255), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "receipt_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("ordinal >= 1", name=op.f("ck_review_rounds_ordinal_positive")),
        sa.ForeignKeyConstraint(
            ["superdocs_job_id"],
            ["superdocs_jobs.id"],
            name=op.f("fk_review_rounds_superdocs_job_id_superdocs_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_review_rounds_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_rounds")),
        sa.UniqueConstraint("superdocs_job_id", "ordinal", name="uq_review_round_job_ordinal"),
    )
    op.create_index(
        op.f("ix_review_rounds_sync_run_id"), "review_rounds", ["sync_run_id"], unique=False
    )
    op.create_table(
        "verification_results",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("write_plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PASSED",
                "FAILED",
                name="verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("verifier_version", sa.String(length=128), nullable=False),
        sa.Column("expected_canonical_sha256", sa.String(length=64), nullable=False),
        sa.Column("actual_canonical_sha256", sa.String(length=64), nullable=True),
        sa.Column("actual_revision_id", sa.Text(), nullable=True),
        sa.Column(
            "report",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_verification_results_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["write_plan_id"],
            ["write_plans.id"],
            name=op.f("fk_verification_results_write_plan_id_write_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_results")),
    )
    op.create_index(
        op.f("ix_verification_results_sync_run_id"),
        "verification_results",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "proposed_changes",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("superdocs_job_id", sa.Uuid(), nullable=False),
        sa.Column("review_round_id", sa.Uuid(), nullable=False),
        sa.Column("target_document_id", sa.Uuid(), nullable=False),
        sa.Column("replaces_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("superdocs_change_id", sa.String(length=255), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "edit",
                "create",
                "delete",
                name="proposal_operation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("chunk_id", sa.String(length=255), nullable=True),
        sa.Column("old_html", sa.Text(), nullable=True),
        sa.Column("new_html", sa.Text(), nullable=True),
        sa.Column("ai_explanation", sa.Text(), nullable=True),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaces_proposal_id"],
            ["proposed_changes.id"],
            name=op.f("fk_proposed_changes_replaces_proposal_id_proposed_changes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_round_id"],
            ["review_rounds.id"],
            name=op.f("fk_proposed_changes_review_round_id_review_rounds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superdocs_job_id"],
            ["superdocs_jobs.id"],
            name=op.f("fk_proposed_changes_superdocs_job_id_superdocs_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_proposed_changes_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_document_id"],
            ["superdocs_documents.id"],
            name=op.f("fk_proposed_changes_target_document_id_superdocs_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposed_changes")),
        sa.UniqueConstraint(
            "superdocs_job_id", "superdocs_change_id", name="uq_proposed_change_job_external_id"
        ),
    )
    op.create_index(
        op.f("ix_proposed_changes_sync_run_id"), "proposed_changes", ["sync_run_id"], unique=False
    )
    op.create_table(
        "review_decisions",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_change_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE",
                "REJECT",
                name="change_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewer_subject", sa.String(length=255), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("decision_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposed_change_id"],
            ["proposed_changes.id"],
            name=op.f("fk_review_decisions_proposed_change_id_proposed_changes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
            name=op.f("fk_review_decisions_sync_run_id_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
        sa.UniqueConstraint("proposed_change_id", name="uq_review_decision_proposal"),
    )
    op.create_index(
        op.f("ix_review_decisions_sync_run_id"), "review_decisions", ["sync_run_id"], unique=False
    )
    op.create_table(
        "write_plan_lineage",
        sa.Column("write_plan_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_change_id", sa.Uuid(), nullable=False),
        sa.Column("review_decision_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposed_change_id"],
            ["proposed_changes.id"],
            name=op.f("fk_write_plan_lineage_proposed_change_id_proposed_changes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_decision_id"],
            ["review_decisions.id"],
            name=op.f("fk_write_plan_lineage_review_decision_id_review_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["write_plan_id"],
            ["write_plans.id"],
            name=op.f("fk_write_plan_lineage_write_plan_id_write_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_write_plan_lineage")),
        sa.UniqueConstraint(
            "write_plan_id", "proposed_change_id", name="uq_write_plan_lineage_proposal"
        ),
    )
    op.create_index(
        op.f("ix_write_plan_lineage_write_plan_id"),
        "write_plan_lineage",
        ["write_plan_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text("""
            CREATE FUNCTION docrelay_reject_immutable_update()
            RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'immutable DocRelay evidence rows cannot be updated';
            END;
            $$ LANGUAGE plpgsql
        """)
        )
        for table_name in (
            "mapping_proofs",
            "proposed_changes",
            "review_decisions",
            "write_plans",
            "write_plan_lineage",
        ):
            op.execute(
                sa.text(
                    f"CREATE TRIGGER trg_{table_name}_immutable "
                    f"BEFORE UPDATE ON {table_name} FOR EACH ROW "
                    "EXECUTE FUNCTION docrelay_reject_immutable_update()"
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_write_plan_lineage_write_plan_id"), table_name="write_plan_lineage")
    op.drop_table("write_plan_lineage")
    op.drop_index(op.f("ix_review_decisions_sync_run_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_proposed_changes_sync_run_id"), table_name="proposed_changes")
    op.drop_table("proposed_changes")
    op.drop_index(op.f("ix_verification_results_sync_run_id"), table_name="verification_results")
    op.drop_table("verification_results")
    op.drop_index(op.f("ix_review_rounds_sync_run_id"), table_name="review_rounds")
    op.drop_table("review_rounds")
    op.drop_index(op.f("ix_backups_sync_run_id"), table_name="backups")
    op.drop_table("backups")
    op.drop_table("write_plans")
    op.drop_index(op.f("ix_superdocs_jobs_sync_run_id"), table_name="superdocs_jobs")
    op.drop_table("superdocs_jobs")
    op.drop_index(
        op.f("ix_superdocs_documents_superdocs_session_id"), table_name="superdocs_documents"
    )
    op.drop_table("superdocs_documents")
    op.drop_index(op.f("ix_mapping_proofs_sync_run_id"), table_name="mapping_proofs")
    op.drop_table("mapping_proofs")
    op.drop_table("superdocs_sessions")
    op.drop_index(op.f("ix_source_snapshots_cloud_document_id"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_index(op.f("ix_run_transitions_sync_run_id"), table_name="run_transitions")
    op.drop_table("run_transitions")
    op.drop_index(op.f("ix_run_operations_sync_run_id"), table_name="run_operations")
    op.drop_index("ix_run_operations_run_stage", table_name="run_operations")
    op.drop_table("run_operations")
    op.drop_index(op.f("ix_external_effects_sync_run_id"), table_name="external_effects")
    op.drop_table("external_effects")
    op.drop_index("ix_audit_events_type_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_sync_run_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_connection_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_sync_runs_state"), table_name="sync_runs")
    op.drop_index("ix_sync_runs_document_nonterminal", table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_cloud_document_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_table("watch_cursors")
    op.drop_index(op.f("ix_folder_rules_watch_config_id"), table_name="folder_rules")
    op.drop_table("folder_rules")
    op.drop_index(op.f("ix_watch_configs_connection_id"), table_name="watch_configs")
    op.drop_table("watch_configs")
    op.drop_index(op.f("ix_cloud_documents_connection_id"), table_name="cloud_documents")
    op.drop_table("cloud_documents")
    op.drop_index(op.f("ix_cloud_connections_owner_subject"), table_name="cloud_connections")
    op.drop_table("cloud_connections")
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP FUNCTION docrelay_reject_immutable_update()"))
